//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceClient1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.InterfaceCalc")]
    public interface InterfaceCalc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalc/Add", ReplyAction="http://tempuri.org/InterfaceCalc/AddResponse")]
        double Add(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalc/Add", ReplyAction="http://tempuri.org/InterfaceCalc/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalc/Sub", ReplyAction="http://tempuri.org/InterfaceCalc/SubResponse")]
        double Sub(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalc/Sub", ReplyAction="http://tempuri.org/InterfaceCalc/SubResponse")]
        System.Threading.Tasks.Task<double> SubAsync(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalc/Multiply", ReplyAction="http://tempuri.org/InterfaceCalc/MultiplyResponse")]
        double Multiply(double n1, double n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceCalc/Multiply", ReplyAction="http://tempuri.org/InterfaceCalc/MultiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double n1, double n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterfaceCalcChannel : WcfServiceClient1.ServiceReference2.InterfaceCalc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterfaceCalcClient : System.ServiceModel.ClientBase<WcfServiceClient1.ServiceReference2.InterfaceCalc>, WcfServiceClient1.ServiceReference2.InterfaceCalc {
        
        public InterfaceCalcClient() {
        }
        
        public InterfaceCalcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterfaceCalcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceCalcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterfaceCalcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double n1, double n2) {
            return base.Channel.Add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double n1, double n2) {
            return base.Channel.AddAsync(n1, n2);
        }
        
        public double Sub(double n1, double n2) {
            return base.Channel.Sub(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> SubAsync(double n1, double n2) {
            return base.Channel.SubAsync(n1, n2);
        }
        
        public double Multiply(double n1, double n2) {
            return base.Channel.Multiply(n1, n2);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double n1, double n2) {
            return base.Channel.MultiplyAsync(n1, n2);
        }
    }
}
